version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"     # สำหรับ ESP8266
      - "9001:9001"     # สำหรับ WebSocket (เช่น MQTT Dashboard หรือ Web App)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
